### ISSUE TITLE
Preview video bar does not work 

### ISSUE THREAD

**Issue by danicaoma** [ostreifel/Attachments-Group#16]
When we attach a video, we can see it correctly in the preview without having to download it. An ideal tool for developers and QAs. But the video can not be moved backwards or forwards in any point of the video, something rather uncomfortable in videos of more than 30 seconds.

[20181221_125334.zip](https://github.com/ostreifel/Attachments-Group/files/2702649/20181221_125334.zip)

![2018-12-21_1254](https://user-images.githubusercontent.com/24606416/50341601-a4e35e00-051f-11e9-942f-eb21a9160497.png)

**Comment by ostreifel** [comment]
I think this is an issue with how Azure Devops downloads file attachments
See - 
https://stackoverflow.com/questions/8088364/html5-video-will-not-loop
I was able to create two different video tags on jsfiddle.com
- First video src hosted as a file attachment on Azure Devops
- Second video src using the [sample](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_video) w3schools.com

The devops one does not seek - likely because azure devops was not built with video hosting in mind (see linked stackoverflow) which is unfortunate but expected. Trying to use the dataurl workaround I use for pdf's doesn't seem to improve the situation.

Let me know if you know of any other work arounds I can try otherwise I don't think I'll be able to fix this.
